### PR TITLE
Add http scheme in url

### PR DESCRIPTION
**Pull request by asivaneswaran**
#50

### CODE REVIEW

**Comment by asivaneswaran** [comment]
@DarkGhostHunter Can you take a look and see if we can merge this?

**Comment by asivaneswaran** [comment]
@DarkGhostHunter I fixed the 2 errors related to this MR.

**Comment by asivaneswaran** [comment]
@DarkGhostHunter Can we merge this PR please?

**Comment by asivaneswaran** [comment]
@DarkGhostHunter Would it be possible to merge this please?

**Comment by asivaneswaran** [comment]
Is this package still maintained?

**Comment by DarkGhostHunter** [comment]
> Is this package still maintained?

Yes, but I'm hands full under contract. Once it ends, I will get back into reviewing all PR's across the org.

**Comment by asivaneswaran** [comment]
Hey, any news on this?

We are using the package and we need to start testing our tickets and we can't test until these PR's are merged.

I am not trying to rush you or anything, just wondering if I need to fork it until you can merge these or not.

**Comment by DarkGhostHunter** [comment]
Fork it. I’m still under contract since the project got delayed. Italo Baeza C.El 08-11-2023, a la(s) 15:31, asivaneswaran ***@***.***> escribió:﻿
Hey, any news on this?
We are using the package and we need to start testing our tickets and we can't test until these PR's are merged.
I am not trying to rush you or anything, just wondering if I need to fork it until you can merge these or not.

**Comment by DarkGhostHunter** [comment]
Went my own way #65

**Pull request closed without merging**
