### PR TITLE
[3.x] Removes lingering error-prone string

### PR DESCRIPTION
**Pull request by DarkGhostHunter**
Left out from #91

### CODE REVIEW

**Comment by szepeviktor** [comment]
Very lingering.
Let's do something about it!

**Comment by DarkGhostHunter** [comment]
> Very lingering.
> 
> Let's do something about it!

Already did. Not longer lingering.

**Comment by szepeviktor** [comment]
I mean in an automated way without you.

**Comment by szepeviktor** [comment]
@DarkGhostHunter Turns out it is a goto label 😲 
https://github.com/phpstan/phpstan/issues/11406#issuecomment-2254989636

**Comment by DarkGhostHunter** [comment]
Thanks for pushing it upstream ;)

**Pull request merged**
